spring.application.name=workshop-app

server.port=${SERVER_PORT:8080}

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://postgres:5432/spring_boot_dev}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:spring_boot}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:spring_boot_dev_password}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false

management.endpoints.web.exposure.include=health,info
