services:
  postgres:
    image: postgres:18
    container_name: spring-dev-postgres

    environment:
      POSTGRES_DB: spring_boot_dev
      POSTGRES_USER: spring_boot
      POSTGRES_PASSWORD: spring_boot_dev_password

    ports:
      - "5432:5432"

    volumes:
      - spring-dev-postgres-data:/var/lib/postgresql/data

    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"
        ]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 10s

    networks:
      - spring-dev-network

    restart: unless-stopped


volumes:
  spring-dev-postgres-data:
    name: spring-dev-postgres-data


networks:
  spring-dev-network:
    name: spring-dev-network
    driver: bridge
